- 1.1.18
- _NAME: LIFT VERTICAL ERGONOMIC MOUSE
  _absent: [hi-res-scroll, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, scroll-ratchet-torque, smart-shift, thumb-scroll-invert,
    thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi_extended, speed-change, backlight, backlight_level, backlight_duration_hands_out,
    backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control, rgb_zone_, brightness_control, per-key-lighting,
    fn-swap, persistent-remappable-keys, disable-keyboard-keys, force-sensing, crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform,
    gesture2-gestures, gesture2-divert, gesture2-params, haptic-level, haptic-play, sidetone, equalizer, adc_power_management]
  _battery: 4100
  _modelId: B03100000000
  _sensitive: {change-host: false, divert-keys: true, dpi: true, reprogrammable-keys: false}
  _serial: 75DE8EBA
  _unitId: 75DE8EBA
  _wpid: B031
  change-host: null
  divert-keys: {82: 0, 83: 1, 86: 1, 253: 0}
  dpi: 3000
  lowres-scroll-mode: false
  reprogrammable-keys: {82: 82, 83: 83, 86: 86, 253: 253}
